### ISSUE TITLE
Google Colaboratory support

### ISSUE THREAD

**Issue by korakot** [fastai/fast_progress#1]
When I used `fast progress` in Google Colaboratory, I found this error
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-d93e865ab2ed> in <module>()
----> 1 from fast_progress import master_bar, progress_bar
      2 from time import sleep

/content/fast_progress.py in <module>()
      7 
      8 if IN_NOTEBOOK:
----> 9     from ipywidgets import widgets, IntProgress, HBox, HTML, VBox
     10     from IPython.display import clear_output
     11     from ipywidgets.widgets.interaction import show_inline_matplotlib_plots

ModuleNotFoundError: No module named 'ipywidgets'
```

So, please also check that it's within Colab, and revert to console version.
Colab can display HTML just fine, and also allow JS<->Python communication.
So, someone can try to implement a Colab-specific version as well.

**Comment by sgugger** [comment]
The whole thing depends on ipywidget, so if it's not available in Colab, the best we can do is the console version.
I've changed the code to try all the imports before deciding the mode (notebook or console), this should fix this issue.
