### ISSUE TITLE
Plot placement

### ISSUE THREAD

**Issue by laol777** [fastai/fast_progress#3]
Is it possible to show plot above all other information?
What I mean:
________________
|plot_____________|
|plot_____________|
|plot_____________|
progress bar1
progress bar2
.....................

**Comment by sgugger** [comment]
Just added a functionality to change the order of the graphic elements, you can check it out in the Example notebook.

**Comment by sgugger** [comment]
Closing this since it's implemented now, let me know if it doesn't work properly.
